# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```


77 for DON’T KNOW and 99 for REFUSED


In [49]:
def proportion_of_education():
    df = pd.read_csv('NISPUF17.csv', index_col=0)
    total = df['EDUC1'].size
    dic = {
        "less than high school":(df[df['EDUC1'] == 1]['EDUC1'].size/total),
        "high school":(df[df['EDUC1'] == 2]['EDUC1'].size/total),
        "more than high school but not college":(df[df['EDUC1'] == 3]['EDUC1'].size/total),
        "college":(df[df['EDUC1'] == 4]['EDUC1'].size/total)
    }
#     df
    # your code goes here
    # YOUR CODE HERE
    return dic
proportion_of_education()

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [1]:
import pandas as pd

In [134]:
df = pd.read_csv('NISPUF17.csv',index_col=0)
df.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [62]:
df.columns

Index(['Unnamed: 0', 'SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D',
       'STRATUM', 'YEAR', 'AGECPOXR', 'HAD_CPOX',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=454)

In [63]:
"EDUC1" in df.columns

True

In [64]:
df['EDUC1'].size

28465

In [65]:
df[df['EDUC1'] == 1]['EDUC1'].size

2904

In [66]:
df[df['EDUC1'] == 2]['EDUC1'].size

4906

In [67]:
df[df['EDUC1'] == 3]['EDUC1'].size

6999

In [68]:
df[df['EDUC1'] == 4]['EDUC1'].size

13656

In [69]:
df['MARITAL2'].unique()

array([2, 1])

In [ ]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [105]:
def average_influenza_doses():
    breast = df[df['CBF_01'] == 1]
    nobreast = df[df['CBF_01'] == 2]
#     a = breast['P_NUMFLU'].dropna().sum()/len(breast['P_NUMFLU'].dropna())
#     b = nobreast['P_NUMFLU'].dropna().sum()/len(breast['P_NUMFLU'].dropna())
    a = breast['P_NUMFLU'].mean()
    b = nobreast['P_NUMFLU'].mean()

    return (a,b)
average_influenza_doses()

(1.8799187420058687, 1.5963945918878317)

In [ ]:
(1.8799187420058687, 0.23986156045444285)

In [70]:
df['CBF_01'].unique()

array([ 1,  2, 99, 77])

In [96]:
breast = df[df['CBF_01'] == 1]
nobreast = df[df['CBF_01'] == 2]

In [102]:
a = breast['P_NUMFLU'].dropna().sum()/len(breast['P_NUMFLU'].dropna())
b = nobreast['P_NUMFLU'].dropna().sum()/len(breast['P_NUMFLU'].dropna())
(a,b)

(1.8799187420058687, 0.23986156045444285)

In [73]:
df['P_NUMFLU'].unique()

array([nan,  3.,  0.,  2.,  1.,  4.,  5.,  6.])

In [74]:
# dfx = df.set_index(['CBF_01','P_NUMFLU'])
# dfx

In [93]:
df[(df['CBF_01'] == 2)&(df['CBF_01'] == 6)]

Empty DataFrame
Columns: [Unnamed: 0, SEQNUMC, SEQNUMHH, PDAT, PROVWT_D, RDDWT_D, STRATUM, YEAR, AGECPOXR, HAD_CPOX, AGEGRP, BF_ENDR06, BF_EXCLR06, BF_FORMR08, BFENDFL06, BFFORMFL06, C1R, C5R, CBF_01, CEN_REG, CHILDNM, CWIC_01, CWIC_02, EDUC1, FRSTBRN, I_HISP_K, INCPORAR, INCPORAR_I, INCPOV1, INCQ298A, LANGUAGE, M_AGEGRP2, MARITAL2, MOBIL_I, NUM_PHONE, NUM_CELLS_HH, NUM_CELLS_PARENTS, RACE_K, RACEETHK, RENT_OWN, SEX, ESTIAP17, EST_GRANT, STATE, D6R, D7, N_PRVR, PROV_FAC, REGISTRY, VFC_ORDER, HEP_BRTH, HEP_FLAG, P_NUHEPX, P_NUHIBX, P_NUHPHB, P_NUMDAH, P_NUMDHI, P_NUMDIH, P_NUMDTA, P_NUMDTP, P_NUMFLU, P_NUMFLUL, P_NUMFLUM, P_NUMFLUN, P_NUMHEA, P_NUMHEN, P_NUMHEP, P_NUMHG, P_NUMHHY, P_NUMHIB, P_NUMHIN, P_NUMHION, P_NUMHM, P_NUMHS, P_NUMIPV, P_NUMMCN, P_NUMMMR, P_NUMMMRX, P_NUMMMX, P_NUMMP, P_NUMMPR, P_NUMMRV, P_NUMMS, P_NUMMSM, P_NUMMSR, P_NUMOLN, P_NUMOPV, P_NUMPCV, P_NUMPCP, P_NUMPCC, P_NUMPCC7, P_NUMPCC13, P_NUMPCCN, P_NUMPCN, P_NUMPOL, P_NUMRB, P_NUMRG, P_NUMRM, P_NUMRO, P_NUMROT, ...]
Index: []

[0 rows x 454 columns]

In [ ]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [ ]:
def chickenpox_by_sex():
    male = df[df['SEX'] == 1]
    female = df[df['SEX'] == 2]
    vaccinatedfemale = female[female['P_NUMVRC'] >=1]
    vaccinatedmale = male[male['P_NUMVRC'] >=1]
    result =  {
                "male":len(vaccinatedmale[vaccinatedmale['HAD_CPOX']==1])/len(vaccinatedmale[vaccinatedmale['HAD_CPOX']==2]),
               "female":len(vaccinatedfemale[vaccinatedfemale['HAD_CPOX']==1])/len(vaccinatedfemale[vaccinatedfemale['HAD_CPOX']==2])
            }
    return result

In [108]:
male = df[df['SEX'] == 1]
female = df[df['SEX'] == 2]

In [115]:
vaccinatedfemale = female[female['P_NUMVRC'] >=1]
vaccinatedmale = male[male['P_NUMVRC'] >=1]

In [116]:
print(vaccinatedfemale['P_NUMVRC'].unique())
print(vaccinatedmale['P_NUMVRC'].unique())

[1. 2.]
[1. 2. 3.]


In [121]:
print(len(vaccinatedfemale[vaccinatedfemale['HAD_CPOX']==1])/len(vaccinatedfemale[vaccinatedfemale['HAD_CPOX']==2]))
print(len(vaccinatedmale[vaccinatedmale['HAD_CPOX']==1])/len(vaccinatedmale[vaccinatedmale['HAD_CPOX']==2]))

0.0077918259335489565
0.009675583380762664


In [ ]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [166]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    df = pd.read_csv('NISPUF17.csv',index_col=0)
    
    # this is just an example dataframe
#     df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
#                    "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

#     # here is some stub code to actually run the correlation
#     corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # this is just an example dataframe
    hadcpox = df[df['HAD_CPOX'] != 77]
    hadcpox = hadcpox[hadcpox['HAD_CPOX'] != 99]
    hadcpox = hadcpox[hadcpox['P_NUMVRC'].isnull() == False]
#     hadcpox['HAD_CPOX'].unique()
    df=pd.DataFrame({"had_chickenpox_column":hadcpox['HAD_CPOX'],
                   "num_chickenpox_vaccine_column":hadcpox['P_NUMVRC']})

    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    return corr,pval
corr_chickenpox()

(0.07044873460148016, 2.7780263182891086e-18)

In [147]:
df['HAD_CPOX'].unique()

array([ 2,  1, 77, 99])

In [155]:
hadcpox = df[df['HAD_CPOX'] != 77]
hadcpox = hadcpox[hadcpox['HAD_CPOX'] != 99]
hadcpox

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
1       128521     12852     2         NaN  235.916956     1031  2017   
2        10741      1074     2         NaN  957.353840     1068  2017   
3       220011     22001     2         NaN  189.611299     1050  2017   
4        86131      8613     1  675.430817  333.447418     1040  2017   
5       227141     22714     1  482.617748  278.768063     1008  2017   
...        ...       ...   ...         ...         ...      ...   ...   
28461    19141      1914     2         NaN   21.188088     2062  2017   
28462   121401     12140     2         NaN   26.503010     2004  2017   
28463   128831     12883     2         NaN   27.520652     2004  2017   
28464    82921      8292     2         NaN   22.390587     2062  2017   
28465   244621     24462     2         NaN   27.520652     2004  2017   

       AGECPOXR  HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  \
1           NaN         2       1  ...                        NaN      NaN   
2           NaN         2       1  ...                        NaN      NaN   
3           NaN         2       3  ...                        NaN      NaN   
4           NaN         2       1  ...                        NaN      NaN   
5           NaN         2       1  ...                        NaN      NaN   
...         ...       ...     ...  ...      ...      ...      ...      ...   
28461       NaN         2       3  ...                        NaN      NaN   
28462       NaN         2       3  ...                        NaN      NaN   
28463       NaN         2       3  ...                        NaN      NaN   
28464       NaN         2       3  ...                        NaN      NaN   
28465       NaN         2       3  ...                        NaN      NaN   

       XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1          NaN      NaN      NaN      NaN          NaN          NaN  
2          NaN      NaN      NaN      NaN          NaN          NaN  
3          NaN      NaN      NaN      NaN          NaN          NaN  
4          NaN      NaN      NaN      NaN          1.0          2.0  
5          NaN      NaN      NaN      NaN          2.0          1.0  
...        ...      ...      ...      ...          ...          ...  
28461      NaN      NaN      NaN      NaN          NaN          NaN  
28462      NaN      NaN      NaN      NaN          NaN          NaN  
28463      NaN      NaN      NaN      NaN          NaN          NaN  
28464      NaN      NaN      NaN      NaN          NaN          NaN  
28465      NaN      NaN      NaN      NaN          NaN          NaN  

[28357 rows x 453 columns]

In [161]:
hadcpox

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
1       128521     12852     2         NaN  235.916956     1031  2017   
2        10741      1074     2         NaN  957.353840     1068  2017   
3       220011     22001     2         NaN  189.611299     1050  2017   
4        86131      8613     1  675.430817  333.447418     1040  2017   
5       227141     22714     1  482.617748  278.768063     1008  2017   
...        ...       ...   ...         ...         ...      ...   ...   
28461    19141      1914     2         NaN   21.188088     2062  2017   
28462   121401     12140     2         NaN   26.503010     2004  2017   
28463   128831     12883     2         NaN   27.520652     2004  2017   
28464    82921      8292     2         NaN   22.390587     2062  2017   
28465   244621     24462     2         NaN   27.520652     2004  2017   

       AGECPOXR  HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  \
1           NaN         2       1  ...                        NaN      NaN   
2           NaN         2       1  ...                        NaN      NaN   
3           NaN         2       3  ...                        NaN      NaN   
4           NaN         2       1  ...                        NaN      NaN   
5           NaN         2       1  ...                        NaN      NaN   
...         ...       ...     ...  ...      ...      ...      ...      ...   
28461       NaN         2       3  ...                        NaN      NaN   
28462       NaN         2       3  ...                        NaN      NaN   
28463       NaN         2       3  ...                        NaN      NaN   
28464       NaN         2       3  ...                        NaN      NaN   
28465       NaN         2       3  ...                        NaN      NaN   

       XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1          NaN      NaN      NaN      NaN          NaN          NaN  
2          NaN      NaN      NaN      NaN          NaN          NaN  
3          NaN      NaN      NaN      NaN          NaN          NaN  
4          NaN      NaN      NaN      NaN          1.0          2.0  
5          NaN      NaN      NaN      NaN          2.0          1.0  
...        ...      ...      ...      ...          ...          ...  
28461      NaN      NaN      NaN      NaN          NaN          NaN  
28462      NaN      NaN      NaN      NaN          NaN          NaN  
28463      NaN      NaN      NaN      NaN          NaN          NaN  
28464      NaN      NaN      NaN      NaN          NaN          NaN  
28465      NaN      NaN      NaN      NaN          NaN          NaN  

[28357 rows x 453 columns]

In [162]:
hadcpox = hadcpox[hadcpox['P_NUMVRC'].isnull() == False]
hadcpox

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
4        86131      8613     1  675.430817  333.447418     1040  2017   
5       227141     22714     1  482.617748  278.768063     1008  2017   
7       221381     22138     1  516.427723  248.916038     1008  2017   
8       182861     18286     1  313.225832  163.213401     1001  2017   
9       161121     16112     1  978.042448  718.616990     1016  2017   
...        ...       ...   ...         ...         ...      ...   ...   
28447   193801     19380     1  321.058203  110.009181     2047  2017   
28448   136841     13684     1  593.426753  337.255316     2031  2017   
28450   132081     13208     1  166.681363   96.330007     2059  2017   
28453    82151      8215     1  335.456813  159.895243     2056  2017   
28455   191451     19145     1   59.626969   29.187316     2074  2017   

       AGECPOXR  HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  \
4           NaN         2       1  ...                        NaN      NaN   
5           NaN         2       1  ...                        NaN      NaN   
7           NaN         2       3  ...                        NaN      NaN   
8           NaN         2       2  ...                        NaN      NaN   
9           3.0         1       1  ...                        NaN      NaN   
...         ...       ...     ...  ...      ...      ...      ...      ...   
28447       NaN         2       2  ...                        NaN      NaN   
28448       NaN         2       2  ...                        NaN      NaN   
28450       NaN         2       3  ...                        NaN      NaN   
28453       NaN         2       2  ...                        NaN      NaN   
28455       NaN         2       2  ...                        NaN      NaN   

       XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
4          NaN      NaN      NaN      NaN          1.0          2.0  
5          NaN      NaN      NaN      NaN          2.0          1.0  
7          NaN      NaN      NaN      NaN          1.0          2.0  
8          NaN      NaN      NaN      NaN          3.0          2.0  
9          NaN      NaN      NaN      NaN          4.0          4.0  
...        ...      ...      ...      ...          ...          ...  
28447      NaN      NaN      NaN      NaN          2.0          2.0  
28448      NaN      NaN      NaN      NaN          1.0          2.0  
28450      NaN      NaN      NaN      NaN          1.0          2.0  
28453      NaN      NaN      NaN      NaN          1.0          2.0  
28455      NaN      NaN      NaN      NaN          3.0          2.0  

[15286 rows x 453 columns]

In [163]:
hadcpox['P_NUMVRC']

array([1., 0., 2., 3.])

In [ ]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."
